### ISSUE TITLE
Correct Python Version?

### ISSUE THREAD

**Issue by yzimmermann** [JanoschMenke/metis#4]
According to `pyproject.toml`, metis should work with Python 3.8, but it seems like you need 3.9 at least:

> Traceback (most recent call last):
  File "/Users/yoel/.pyenv/versions/3.8.10/bin/metis", line 5, in <module>
    from metis.metis import launch
  File "/Users/yoel/.pyenv/versions/3.8.10/lib/python3.8/site-packages/metis/metis.py", line 13, in <module>
    from metis.backend import Backend
  File "/Users/yoel/.pyenv/versions/3.8.10/lib/python3.8/site-packages/metis/backend/__init__.py", line 1, in <module>
    from .backend_class import Backend
  File "/Users/yoel/.pyenv/versions/3.8.10/lib/python3.8/site-packages/metis/backend/backend_class.py", line 1, in <module>
    from metis.utils import (
  File "/Users/yoel/.pyenv/versions/3.8.10/lib/python3.8/site-packages/metis/utils/data.py", line 11, in <module>
    from metis.reinvent_connect import train_rf as trf
  File "/Users/yoel/.pyenv/versions/3.8.10/lib/python3.8/site-packages/metis/reinvent_connect/train_rf.py", line 199, in <module>
    class ecfp_generator:
  File "/Users/yoel/.pyenv/versions/3.8.10/lib/python3.8/site-packages/metis/reinvent_connect/train_rf.py", line 212, in ecfp_generator
    def get_fingerprints(self, smiles: List[str]) -> np.ndarray[np.int32]:
TypeError: Type subscription requires python >= 3.9

**Comment by JanoschMenke** [comment]
It should be `>= 3.8, <3.11`. I usually run it with Python 3.10. Have you had issues with a particular version?

**Comment by yzimmermann** [comment]
> It should be `>= 3.8, <3.11`. I usually run it with Python 3.10. Have you had issues with a particular version?

See above. I accidentally posted too early.

**Comment by JanoschMenke** [comment]
Yeah I saw it haha I updated my original comment.

**Comment by JanoschMenke** [comment]
I changed the requirements

**Comment by JanoschMenke** [comment]
That works as well, although I just removed the numpy type and "upgraded" `tuple` to `Tuple`

Yeah, I saw the ARM issue as well, which is only true for PySide2 versions 15.5.1 and 15.5.2.
I am adding a statement that checks whether metis is running on a MacOS and uses the PySide2 versions in question

**Comment by JanoschMenke** [comment]
See #5 The updated code should be robust to Macs with PySide2 5.15.2.1

However the issue seems to be with Python3.8 + Mac Silicon + PySide2 5.15.2.1

**Comment by yzimmermann** [comment]
Looks good!
